[package]
name = "whamm_core"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
once_cell = { workspace = true }
wasm-bindgen = { workspace = true }
log = { workspace = true }
itertools = { workspace = true }
