[package]
name = "add"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
doc = false
name = "cf"
path = "src/main.rs"

[dependencies]
wasm-bindgen = { workspace = true }
