[package]
name = "whamm_core_impl"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
once_cell = "1.3.1"
wasm-bindgen = "0.2"
log = "0.4.20"
itertools = "0.14.0"
