[package]
name = "wasm_runner"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "wasm_runner"
path = "src/main.rs"
#required-features = ["exe"]

[dependencies]
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasi-common = { workspace = true }
